import PDFDocument from 'pdfkit'
import { storage } from '../admin'
import { getCompanySettings, fetchLogoBuffer } from './companySettings'
import { registerGeneratedFile } from '../files/registerGeneratedFile'
import {
  CONTENT_W,
  MARGIN_L,
  RIGHT_EDGE,
  drawBrandedFooter,
  drawBrandedHeader,
} from './layout'

export interface GenerateTermsAcceptanceInput {
  customerId: string
  quoteId: string
  quoteNumber?: string | null
  approvedAt: Date
  approvedByName: string
  approvedByEmail?: string | null
  deliveryContactName: string
  deliveryContactPhone?: string | null
  deliveryContactEmail?: string | null
  primaryCommunicationMethod: 'email' | 'phone' | 'text'
  quoteProvidedTo?: string | null
  documentLabel?: string
  documentVersion?: string
}

export async function generateTermsAcceptancePdf(
  input: GenerateTermsAcceptanceInput,
): Promise<{ url: string; storagePath: string; fileName: string }> {
  const company = await getCompanySettings()
  const logoBuf = await fetchLogoBuffer(company.logoUrl)

  const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 0, size: 'LETTER' })
    const chunks: Buffer[] = []

    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const quoteRef = input.quoteNumber || input.quoteId
    const dividerY = drawBrandedHeader(
      doc,
      company,
      logoBuf,
      'TERMS ACCEPTED',
      `Quote #${quoteRef}`,
    )

    const acceptedDate = input.approvedAt.toLocaleString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    })

    const rows: Array<[string, string]> = [
      ['Document', input.documentLabel || 'Ohio Gas Supply Terms & Conditions'],
      ['Version', input.documentVersion || 'current'],
      ['Accepted At', acceptedDate],
      ['Approved By', input.approvedByName],
      ['Approval Email', input.approvedByEmail || 'Not provided'],
      ['Delivery Contact', input.deliveryContactName],
      ['Delivery Phone', input.deliveryContactPhone || 'Not provided'],
      ['Delivery Email', input.deliveryContactEmail || 'Not provided'],
      ['Communication', input.primaryCommunicationMethod === 'phone'
        ? 'Phone'
        : input.primaryCommunicationMethod === 'text'
          ? 'Text'
          : 'Email'],
      ['Quote Provided To', input.quoteProvidedTo || input.approvedByName],
    ]

    let rowY = dividerY + 24
    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#333333')
      .text(
        'This document confirms the customer accepted Ohio Gas Supply terms and conditions during quote approval.',
        MARGIN_L,
        rowY,
        { width: CONTENT_W, lineGap: 3 },
      )

    rowY += 44
    for (const [label, value] of rows) {
      doc
        .fontSize(8)
        .font('Helvetica-Bold')
        .fillColor('#888888')
        .text(label.toUpperCase(), MARGIN_L, rowY, { width: 150 })
      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#111111')
        .text(value, MARGIN_L + 156, rowY, { width: RIGHT_EDGE - (MARGIN_L + 156) })

      rowY += 26
      doc
        .moveTo(MARGIN_L, rowY - 8)
        .lineTo(RIGHT_EDGE, rowY - 8)
        .strokeColor('#ECECEC')
        .lineWidth(0.5)
        .stroke()
    }

    if (company.termsAndConditions) {
      rowY += 8
      doc
        .fontSize(7.5)
        .font('Helvetica-Bold')
        .fillColor('#999999')
        .text('ACCEPTED TERMS SUMMARY', MARGIN_L, rowY)
      rowY += 14
      doc
        .fontSize(8)
        .font('Helvetica')
        .fillColor('#555555')
        .text(company.termsAndConditions, MARGIN_L, rowY, {
          width: CONTENT_W,
          height: 220,
          ellipsis: true,
          lineGap: 2,
        })
    }

    drawBrandedFooter(doc, company, 'Terms acceptance record generated by the OGS Portal.')
    doc.end()
  })

  const acceptedDateKey = input.approvedAt.toISOString().slice(0, 10)
  const fileName = `Terms-Conditions-Accepted-${acceptedDateKey}.pdf`
  const storagePath = `ogs-portal/customers/${input.customerId}/terms-acceptance/${input.quoteId}.pdf`
  const fileRef = storage.bucket().file(storagePath)
  const downloadToken = crypto.randomUUID()

  await fileRef.save(pdfBuffer, {
    contentType: 'application/pdf',
    metadata: {
      cacheControl: 'private, max-age=0',
      metadata: {
        customerId: input.customerId,
        quoteId: input.quoteId,
        firebaseStorageDownloadTokens: downloadToken,
      },
    },
  })

  const bucket = storage.bucket().name
  const encodedPath = encodeURIComponent(storagePath)
  const url = `https://firebasestorage.googleapis.com/v0/b/${bucket}/o/${encodedPath}?alt=media&token=${downloadToken}`

  await registerGeneratedFile({
    targets: [
      { entityType: 'customer', entityId: input.customerId },
      { entityType: 'quote', entityId: input.quoteId },
    ],
    fileType: 'contract',
    url,
    storagePath,
    fileName,
    mimeType: 'application/pdf',
    sizeBytes: pdfBuffer.length,
    metadata: {
      linkedEntityType: 'quote',
      linkedEntityId: input.quoteId,
      customerId: input.customerId,
      documentKind: 'terms-acceptance',
      documentLabel: input.documentLabel || 'Terms & Conditions Acceptance',
      documentVersion: input.documentVersion || 'current',
    },
  })

  return { url, storagePath, fileName }
}
